languages2 =
  "И ß č š ž ň å ø æ ä ë ö ü ć ś á é í ó ú ý â ê à ė ż ū ă ğ ã õ ç ę ş ļ Ł ħ đ ð";
// https://www.lexilogos.com/clavier/slovensky.htm

languages = [
  [null, "č"],
  [null, "š"],
  [null, "ă"],
  [null, "ğ"],
  [null, "ć"],
  [null, "ś"],
  [null, "ç"],
  [null, "ę"],
  [null, "ş"],
  [null, "ļ"],
  [null, "å"],
  [null, "ä"],
  [null, "ë"],
  [null, "ö"],
  [null, "ü"],
  [null, "á"],
  [null, "é"],
  [null, "í"],
  [null, "â"],
  [null, "ė"],
  [null, "ż"],
  [null, "ū"],
  [null, "ã"],
  [null, "õ"],
  [null, "ø"],
  [null, "æ"],
  [null, "Ł"],
  [null, "ħ"],
  [null, "đ"],
  [null, "И"],
  //[null, "đ"],
  /*
  [null, "И", "Й"],
  [null, "И", "Я"],
  [null, "И", "ІЇ"],
  [null, "И", "ЁёЭ"],
  [null, "И", "ЅЃЌ"],
  [null, "И", "Ђђћ"],
  [null, "И", "Ң"],
  [null, "И", "Ъ"],
  [null, "И", "Ы"],
  [null, "И", "ЉЊЏЈ"],
  [null, "И", "ЩЬЮЯЙ"],
  [null, "И", "ӨҮ"],
  [null, "И", "ҐЄІЇ"],
  */
  [null, "ß"]
];
